apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

images:
  - name: quarkus
    newName: image-registry.openshift-image-registry.svc:5000/atp-dev/code-with-quarkus
    newTag: 0.0.0
