apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base
  - http-route.yaml
  - auth-policy.yaml
  - dns-healthcheck.yaml
  - rate-limit-policy.yaml

images:
  - name: quarkus
    # newName: image-registry.openshift-image-registry.svc:5000/atp-dev/code-with-quarkus
    newName: quay.io/rh_ee_lfalero/code-with-quarkus
    newTag: 1.0.0
