apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: code-with-quarkus
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: code-with-quarkus
  defaults:
    strategy: merge
    limits:
      # Límite diario por usuario autenticado (scraping/bulk)
      "daily-ceiling":
        rates:
          - limit: 10
            window: 60s # 24h
          # - limit: 1000
          #   window: 86400s # 24h
        counters:
          - expression: auth.identity.userid
